### ISSUE TITLE
Migrate CI

### ISSUE THREAD

**Issue by cleveHEX** [RoboticsBrno/ArduinoLearningKitStarter-library#19]
From travis-ci.org to travis-ci.com

**Comment by JarekParal** [comment]
Why?

**Comment by cleveHEX** [comment]
Travis is moving OSS from `.org` to `.com`. There will be an option for migration soon, it is possible now, but I would have to write an email to them

**Comment by cleveHEX** [comment]
<https://docs.travis-ci.com/user/migrate/open-source-on-travis-ci-com/>
