### ISSUE TITLE
Change LED_BUILTIN on esp32 to be same as on AVR

### ISSUE THREAD

**Issue by cleveHEX** [RoboticsBrno/ArduinoLearningKitStarter-library#22]

**Comment by cleveHEX** [comment]
Also add new options from esp32 dev board to alks.

**Comment by JarekParal** [comment]
What these new options added to beginners? Isn't that counterproductive?

**Comment by cleveHEX** [comment]
Beginners do not have to tamper with these values and it’s better to have them changeable, so you can use alks for everything. Those are only for supporting newer revisions of devkit.

**Comment by JarekParal** [comment]
Ok, it makes sense.
